/* ------------* server/recommendations/recommendations-model.js *-----------
 * methods:
 *
 *  1) getRecMatches:
 *
 *
 */
import debug from 'debug';

import { queryRecommendations } from '../queries/recommendations';

const log = debug('server:rec:model');

/* ------------------------- * getRecMatches * ------------
 *
 * Takes the name of the currently logged in user and fetches
 * all recommended matches from the database.  'Recommended' matches
 * are generated by querying the DB for potential matches and returning
 * users who were liked by a friend separated by 1 degree.
 *
 *  Parameters:
 *    • username | String |
 *    • callback | Function | Exectued on the result of db query.
 *
 *  Returns:
 *    • the resulting db query which resolves into a promise that
 *        executes the callback.
 *
 * --------------------------------------------------------------- */

export async function getRecMatches({ username }, callback) {
  const local = log.extend('getRecMatches');
  local('Accessing user database');

  try {
    const records = await queryRecommendations({ username });
    return callback(records);
  } catch (error) {
    local.extend('error')(error);
    throw error;
  }
}
