const debug = [
  'server:server',
  'server:server:error',
  'server:user:model',
  'server:user:model:getUser',
  'server:user:model:error',
  'server:user:controller',
  'server:search:model',
  'server:search:model:error',
  'server:search:controller',
  'server:rec:model',
  'server:rec:model:error',
  'server:rec:controller',
  'server:passport:local-login',
  'server:messages:model',
  'server:messages:model:error',
  'server:messages:controller',
  'server:matches:model',
  'server:matches:model:error',
  'server:matches:controller',
  'server:location:controller',
  'server:likes:model',
  'server:likes:model:error',
  'server:likes:controller',
  'server:db:initialize',
  'server:bio:model',
  'server:bio:model:error',
  'server:bio:controller',
  'server:queries:users',
  'server:queries:users:queryUser',
  'server:queries:users:queryLikedUsers',
];

module.exports = debug;

