export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_USER = 'GET_USER';
export const GET_RECOMMENDED_USERS = 'GET_RECOMMENDED_USERS';

export const LIKE_USER = 'LIKE_USER';
export const LIKED_USERS = 'LIKED_USERS';

export const FILTER_USERS = 'FILTER_USERS';
export const FILTER_USERS_BY_SEX = 'FILTER_USERS_BY_SEX';
export const FILTER_USERS_BY_MIN_AGE = 'FILTER_USERS_BY_MIN_AGE';
export const FILTER_USERS_BY_MAX_AGE = 'FILTER_USERS_BY_MAX_AGE';
export const FILTER_USERS_BY_CITY = 'FILTER_USERS_BY_CITY';

export const SIGN_UP_USER = 'SIGN_UP_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

export const GET_ALL_MESSAGES = 'GET_ALL_MESSAGES';

export const EDIT_BIO_SUCCESS = 'EDIT_BIO_SUCCESS';
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';

export const TOGGLE_LEFT_NAV = 'TOGGLE_LEFT_NAV';
