export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_USER = 'GET_USER';
export const GET_RECOMMENDED_USERS = 'GET_RECOMMENDED_USERS';

export const LIKE_USER = 'LIKE_USER';
export const GET_LIKED_USERS = 'GET_LIKED_USERS';

export const SIGN_UP_USER = 'SIGN_UP_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

export const GET_ALL_MESSAGES = 'GET_ALL_MESSAGES';
export const GET_SENT_MESSAGES = 'GET_SENT_MESSAGES';

export const EDIT_BIO_SUCCESS = 'EDIT_BIO_SUCCESS';
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';

export const TOGGLE_LEFT_NAV = 'TOGGLE_LEFT_NAV';

export const UPDATE_MINAGE = 'UPDATE_MINAGE';
export const UPDATE_MAXAGE = 'UPDATE_MAXAGE';
export const UPDATE_CITY = 'UPDATE_CITY';
export const CLEAR_FIELDS = 'CLEAR_FIELDS';
